image: java:8

stages:
  - build
  - test
  - deploy

#sbt installing (doesn't currently work)
#before_script:
#  - apt-get update -y
#  - apt-get install apt-transport-https -y
#  ## Install SBT
#  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
#  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
#  - apt-get update -y
#  - apt-get install sbt -y
#  - sbt sbt-version
  
tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

#test:
#  stage: test
#  script:
#    - sbt clean coverage test coverageReport


junit:
  stage: test
  script:
    - sbt test
    
    
#sonarqube_master_job:
#  stage: test
#  only:
#    - master
#  script:
#    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
#https://github.com/gabrie-allaigre/sonar-gitlab-plugin/



recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags
    
update-sonar:
    stage: deploy
    script:
    - export PATH=$PATH:/opt/sonarscanner/sonar-scanner-3.3.0.1492-linux/bin
    - echo $PATH
    - sonar-scanner
    only:
        - master@seng302-2019/team-100
        - dev_branch@seng302-2019/team-100

