image: java:8

stages:
- clean
- test
- build
- deploy
- deploy-server

clean-build:
  stage: clean
  script:
  - if [ -d "target" ]; then rm -r target; fi
  - if [ -d "project/project" ]; then rm -r project/project; fi
  - if [ -d "project/target" ]; then rm -r project/target; fi
  only:
  - master@seng302-2019/team-100

tag_checker:
  stage: build
  script:
  - python tag_checker.py $CI_COMMIT_TAG
  only:
  - tags

junit:
  stage: test
  script:
    - xvfb-run -a sbt jacoco

recent-artifacts:
  stage: deploy
  script:
  - git lfs pull
  - sbt dist
  artifacts:
    paths:
    - target/universal/*.zip
    expire_in: 1 week
  except:
  - tags

release-artifacts:
  stage: deploy
  script:
  - git lfs pull
  - sbt dist
  artifacts:
    paths:
    - target/universal/*.zip
  only:
  - tags

update-sonar:
  stage: deploy
  script:
  - echo $PATH
  - sonar-scanner
  only:
  - master@seng302-2019/team-100
  - dev_branch@seng302-2019/team-100

deploy-master:
  stage: deploy-server
  script:
  - mv target/universal/*.zip ${DEPLOY_DIR}/build/
  - bash scripts/deploy production
  only:
  - master@seng302-2019/team-100

deploy-dev:
  stage: deploy-server
  script:
  - mv target/universal/*.zip ${DEPLOY_DIR}/build/
  - bash scripts/deploy development
  only:
  - dev_branch@seng302-2019/team-100