image: java:8

stages:
  - build
  - test
  - deploy
  - run
  
tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

#junit:
#  stage: test
#  script:
#    - sbt test



recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags
    
update-sonar:
    stage: deploy
    script:
    - export PATH=$PATH:/opt/sonarscanner/sonar-scanner-3.3.0.1492-linux/bin
    - echo $PATH
    - sonar-scanner
    only:
        - master@seng302-2019/team-100
        - dev_branch@seng302-2019/team-100

deploy_zip:
    stage: deploy
    script:
        - cd target/universal
        - unzip seng302-team-100-everyware-0.0.1-SNAPSHOT.zip
    only:
        - master@seng302-2019/team-100

run-project:
    stage: run
    script:
        - cd target/universal/seng302-team-100-everyware-0.0.1-SNAPSHOT/bin
        - ./seng-302-team-100-everyware
    only:
        - master@seng302-2019/team-100