package models.points;

public enum Action {
    DESTINATION_CREATED("DESTINATION_CREATED"),
    TRIP_CREATED("TRIP_CREATED"),
    QUEST_CREATED("QUEST_CREATED"),
    OBJECTIVE_CREATED("OBJECTIVE_CREATED"),
    RIDDLE_SOLVED("RIDDLE_SOLVED"),
    CHECKED_IN("CHECKED_IN"),
    POINTS_GAINED("POINTS_GAINED"),
    LOGIN_STREAK("LOGIN_STREAK"),
    INTERNATIONAL_QUEST_COMPLETED("INTERNATIONAL_QUEST_COMPLETED"),
    LARGE_QUEST_COMPLETED("LARGE_QUEST_COMPLETED"),
    DISTANCE_QUEST_COMPLETED("DISTANCE_QUEST_COMPLETED"),
    QUEST_COMPLETED("QUEST_COMPLETED");


    String value;

    Action(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }
}
