package models.Destinations;

public enum DestinationType {
    AMENITY_AREA, APPELLATION, AREA, BANK, BASIN, BAY, BEACH, BEND, BRIDGE, BUILDING, BUSH, CANAL,
    CANYON, CAPE, CAVE, CHANNEL, CHASM, CITY, CLEARING, CLIFF, COAST_FEATURE, CONSERVATION_PARK,
    CRATER, CROWN_PROTECTED_AREA, DESERT, DISTRICT, ECOLOGICAL_AREA, ESTUARY, FACILITY, FAN, FLAT,
    FORD, FOREST, FORK, GAP, GLACIER, GOVERNMENT_PURPOSE_RESERVE, HILL, HISTORIC_RESERVE, HISTORIC_SITE,
    HOLE, ICE_FEATURE, ISLAND, ISTHMUS, KNOLL, LAKE, LEDGE, LOCALITY, LOCAL_GOVERNMENT, MARINE_FEATURE,
    MARINE_RESERVE, PASS, PENINSULA, PINNACLE, PLACE, PLATEAU, POINT, POOL, PORT, RAILWAY_CROSSING,
    RAILWAY_JUNCTION, RAILWAY_LINE, RAILWAY_STATION, RANGE, RAPID, RECREATION, RECREATION_RESERVE, REEF,
    RESERVE, RIDGE, ROAD, ROADSTEAD, ROCK, SADDLE, SANCTUARY_AREA, SCARP, SCENIC_RESERVE, SCIENTIFIC_RESERVE,
    SEACHANNEL, SHELF, SHOAL, SILL, SITE, SPIT, SPRING, SPUR, STREAM, SUBURB, TOWN, TRACK, TRIG_STATION, TROUGH,
    VALLEY, VILLAGE, WATERFALL, WETLAND, WILDERNESS_AREA, WILDLIFE_MANAGEMENT_AREA

}
