name: Build

on:
  push:
    branches: [ master, dev_branch ]
  pull_request:
    branches: [ master, dev_branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build app
        run: sbt dist
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-build
          path: ./target/universal/*.zip
